#spring.application.name: customer-service
#server.port: 8080
logging.level.root: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
#        exclude: "env,beans"
    jmx:
      exposure:
        include: "*"
          
