version: "3.3"
services:
  mongodb_server:
    image: mongo:6.0.2
    command:  --auth
    ports:
      - 27017:27017
    networks:
      - mongodb-network          
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin_user
      - MONGO_INITDB_ROOT_PASSWORD=admin_pass
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - ./setup-mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
networks:
  mongodb-network:
    name: mongodb-network
    driver: bridge
