version: '3.1'
services:
  mongodb:
    container_name: maoudia-mongodb
    image: mongo:${MONGO_VERSION}
    environment:
      # - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - mongodb-network
    ports:
      - 27017:27017
    volumes:
      - ./data/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      #- ./data/db:/data/db
  mongo-express:
    container_name: maoudia-mongo-express
    image: mongo-express:${MONGO_EXPRESS_VERSION}
    depends_on:
      - mongodb
    networks:
      - mongodb-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=maoudia-mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin_pass
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      #- ME_CONFIG_MONGODB_PORT=27017
      #- ME_CONFIG_OPTIONS_EDITORTHEME='default'
      #- ME_CONFIG_OPTIONS_EDITORTHEME='ambiance'
      #- ME_CONFIG_REQUEST_SIZE='100kb'
      #- ME_CONFIG_SITE_BASEURL='/'
      #- ME_CONFIG_SITE_COOKIESECRET='cookiesecret'
      #- ME_CONFIG_SITE_SESSIONSECRET='sessionsecret'
      #- ME_CONFIG_SITE_SSL_ENABLED=false
      #- ME_CONFIG_SITE_SSL_CRT_PATH=''
      #- ME_CONFIG_SITE_SSL_KEY_PATH=''
      
    ports:
      - 8081:8081
    #volumes:
    #  - ./data/db:/data/db

  product-api:
    container_name: maoudia-product-api
    image: clue/json-server:latest
    ports:
      - 8080:80
    volumes:
      - ./data/product/db.json:/data/db.json
networks:
  mongodb-network:
    name: mongodb-network
