version: "3.8"
services:
  mongodb:
    image: mongo:${MONGO_VERSION}
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      #- ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    expose:
      - 27017
    command: --quiet
    networks:
      - mongodb-network
  mongo-express:
    image: mongo-express:${MONGO_EXPRESS_VERSION}
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    networks:
      - mongodb-network
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin_pass
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      #- ME_CONFIG_MONGODB_PORT=27017
      #- ME_CONFIG_OPTIONS_EDITORTHEME='default'
      #- ME_CONFIG_OPTIONS_EDITORTHEME='ambiance'
      #- ME_CONFIG_REQUEST_SIZE='100kb'
      #- ME_CONFIG_SITE_BASEURL='/'
      #- ME_CONFIG_SITE_COOKIESECRET='cookiesecret'
      #- ME_CONFIG_SITE_SESSIONSECRET='sessionsecret'
      #- ME_CONFIG_SITE_SSL_ENABLED=false
      #- ME_CONFIG_SITE_SSL_CRT_PATH=''
      #- ME_CONFIG_SITE_SSL_KEY_PATH=''
networks:
  mongodb-network:
    name: mongodb-network
